server:
  port: 7001

eureka:
  instance:
    hostname: eureka01 #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要区检索服务
    service-url:
      defaultZone: http://eureka02.com:7002/eureka/
    fetch-registry: false
  server:
    #关闭eureka自我保护机制，默认为true开启
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000