server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  profiles:
    active: prod
    #consul注册中心配置
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jikaigg.springcloud.entities    #所有Entity别名类所在包
