server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  profiles:
    active: dev
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jikaigg.springcloud.entities    #所有Entity别名类所在包
eureka:
  client:
    #表示是否注册到eureka客户端
    register-with-eureka: true
    #是否从eureka抓去已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/