server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource::
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver    #MySQL驱动包
    username: root
    password: YAOjiKAI2@
    url: jdbc:mysql://localhost:3306/jikaigg

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jikaigg.springcloud.entities    #所有Entity别名类所在包