server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  profiles:
    active: dev

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jikaigg.springcloud.entities    #所有Entity别名类所在包