server:
  port: 7002

eureka:
  instance:
    hostname: eureka02 #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要区检索服务
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/
    fetch-registry: false