server:
  port: 8000

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
