spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver    #MySQL驱动包
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jikaigg?serverTimezone=GMT%2B8&useSSL=false